/* =============================================
   The Peoples Butchery — Product Catalog
   295 products across 8 categories
   Generated from Peoples_Butchery_Pricelist_Clean.xlsx
   ============================================= */

export const LOCAL_CATALOG = [
  { stock_code: '103', name: '1.25L Cold Drinks', price: 15, unit: 'Each', category: 'Beverages', image: '', emoji: '🥤' },
  { stock_code: '373', name: '1.25L Stoney', price: 15, unit: 'Each', category: 'Beverages', image: '', emoji: '🥤' },
  { stock_code: '108', name: '1.5L Water', price: 21, unit: 'Each', category: 'Beverages', image: '', emoji: '🥤' },
  { stock_code: '382', name: '1.5L Coke', price: 23, unit: 'Each', category: 'Beverages', image: '', emoji: '🥤' },
  { stock_code: '100', name: '2.5L Coke', price: 32, unit: 'Each', category: 'Beverages', image: '', emoji: '🥤' },
  { stock_code: '101', name: '2L Colddrink', price: 26, unit: 'Each', category: 'Beverages', image: '', emoji: '🥤' },
  { stock_code: '286', name: '300Ml Coke', price: 10, unit: 'Each', category: 'Beverages', image: '', emoji: '🥤' },
  { stock_code: '144', name: '440Ml Coldrinks', price: 14, unit: 'Each', category: 'Beverages', image: '', emoji: '🥤' },
  { stock_code: '319', name: '750 Ml Water', price: 17, unit: 'Each', category: 'Beverages', image: '', emoji: '🥤' },
  { stock_code: '102', name: 'Buddy Colddrink', price: 8, unit: 'Each', category: 'Beverages', image: '', emoji: '🥤' },
  { stock_code: '312', name: 'Can Coke', price: 15, unit: 'Each', category: 'Beverages', image: '', emoji: '🥤' },
  { stock_code: '106', name: 'Juice 330Ml', price: 13, unit: 'Each', category: 'Beverages', image: '', emoji: '🥤' },
  { stock_code: '107', name: 'Water 500Ml', price: 12, unit: 'Each', category: 'Beverages', image: '', emoji: '🥤' },
  { stock_code: '383', name: 'Coke 1.5', price: 23, unit: 'Each', category: 'Beverages', image: '', emoji: '🥤' },
  { stock_code: '1', name: 'Coke 1.5Lt', price: 23, unit: 'Each', category: 'Beverages', image: '', emoji: '🥤' },
  { stock_code: '343', name: '6 Eggs', price: 15, unit: 'Each', category: 'Eggs & Dairy', image: '', emoji: '🥚' },
  { stock_code: '263', name: 'Cheese Puffs', price: 10, unit: 'Each', category: 'Eggs & Dairy', image: '', emoji: '🥚' },
  { stock_code: '345', name: 'Eggs', price: 65, unit: 'Each', category: 'Eggs & Dairy', image: '', emoji: '🥚' },
  { stock_code: '358', name: '5Kg Beenmeel', price: 60, unit: 'Each', category: 'Groceries', image: '', emoji: '🛒' },
  { stock_code: '390', name: 'Kolskoot Spice', price: 25, unit: 'Each', category: 'Groceries', image: '', emoji: '🛒' },
  { stock_code: '194', name: 'Spices', price: 15, unit: 'Each', category: 'Groceries', image: '', emoji: '🛒' },
  { stock_code: '77', name: '1Kg Beef Mala Mogodu', price: 45, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1170', name: '1Kg Chicken Intestines', price: 15, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '297', name: '2.5Kg Beefstew', price: 200, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '362', name: '500G Beef Knuckles', price: 25, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '361', name: '500G Chicken Necks', price: 15, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1103', name: '500G Chilli Wors', price: 35, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '356', name: '500G Pork Stew', price: 27.50, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1091', name: '5Kg Beef Tripe', price: 225, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '281', name: '5Kg Mixed Portion Chicken', price: 300, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1073', name: '5Kg Pork Bones', price: 135, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1053', name: 'Beef Intestines 1Kg', price: 300, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '176', name: 'Beef Intestines 5Kg', price: 175, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '178', name: 'Beef Mala Mogodu Mix 2Kg', price: 80, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1109', name: 'Beef Meaty Bones 1Kg', price: 34, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1038', name: 'Beef Meaty Bones 2.5Kg', price: 85, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '264', name: 'Beef Rib Pie', price: 22, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1139', name: 'Beef Shin', price: 130, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1126', name: 'Beef Stew', price: 100, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1189', name: 'Beef Stew 5Kg', price: 400, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '229', name: 'Beef Stew Bulk', price: 100, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1090', name: 'Beef Tripe 1Kg', price: 50, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '177', name: 'Beef Tripe 2.5Kg', price: 112.50, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1092', name: 'Beef Tripe 500G', price: 25, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '254', name: 'Boerewors Mix', price: 65, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1057', name: 'Braai Wors 1Kg', price: 70, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1095', name: 'Braai Wors 2Kg', price: 140, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1039', name: 'Braai Wors 500G', price: 35, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1102', name: 'Braai Wors Chilli 2Kg', price: 140, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1059', name: 'Braai Wors Chilli 5Kg', price: 300, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '184', name: 'Braai Wors/Kg', price: 70, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1030', name: 'Beef Uncut 5Kg Cavalier /Kg', price: 24, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1001', name: 'Beef Uncut Bones /Kg', price: 28, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '341', name: 'Beef Knuckles 1Kg', price: 50, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '342', name: 'Beef Knuckles 2Kg', price: 100, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '61', name: 'Chic Wors Pap & Gravy', price: 45, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '171', name: 'Chick/Wors/Tam/Pap', price: 60, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '239', name: 'Chicken Curry And Rice', price: 50, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '226', name: 'Chicken Drum Sticks', price: 65, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1167', name: 'Chicken Feet 1Kg', price: 39.95, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '219', name: 'Chicken Fillet 1Kg', price: 75, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '224', name: 'Chicken Fillet 500G', price: 49.99, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1168', name: 'Chicken Gizzards 1Kg', price: 35, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '392', name: 'Chicken Head', price: 25, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1044', name: 'Chicken Hearts 1Kg', price: 30, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1166', name: 'Chicken Hearts 1Kg', price: 35, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1165', name: 'Chicken Liver 1Kg', price: 30, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '246', name: 'Chicken Livers & Pap', price: 35, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1164', name: 'Chicken Necks 1Kg', price: 30, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '364', name: 'Chicken Thighs', price: 55, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '193', name: 'Chicken Wings', price: 81, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '192', name: 'Chicken Wings 500G', price: 63, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '195', name: 'Chicken Wings Merenade', price: 69.99, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1068', name: 'Chilli Wors 1Kg', price: 70, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1121', name: 'Club Steak', price: 125, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '180', name: 'Club Steak And Pap', price: 60, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '378', name: 'Chicken Burgers & Chips', price: 50, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1160', name: 'Droe Wors', price: 239.99, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '240', name: 'Extra Beef Stew', price: 35, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '62', name: 'Extra Chicken', price: 15, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1206', name: 'Gm Boere Wors', price: 95.99, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '340', name: 'Half Chicken/ Chips', price: 80, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '181', name: 'Half Pork Head', price: 60, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1040', name: 'Lamb Bones 2 Kg', price: 60, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '310', name: 'Lamb Bones 5Kg', price: 125.01, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '243', name: 'Lamb Kidney 1Kg', price: 40, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '212', name: 'Lamb Kidney 500G', price: 25, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '322', name: 'Lamb Liver 500G', price: 27.50, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1176', name: 'Lamb Loin Chops', price: 189.99, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '326', name: 'Lamb Mix Mala 1Kg', price: 40, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1147', name: 'Lamb Nuckles 1Kg', price: 50, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1179', name: 'Lamb Stew', price: 140, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '353', name: 'Lamb Trimmings', price: 70, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '37', name: 'Lamb Tripe', price: 30, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '28', name: 'Lamb Tripe 500G', price: 15, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '25', name: 'Lamb Tripe 5Kg', price: 150, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1127', name: 'Lean Beef Mince', price: 91.99, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1013', name: 'Lamb Uncut /Kg', price: 24, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '296', name: 'Marinade Rib', price: 110, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '372', name: 'Marinade Smoked Pork Rib', price: 50, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '58', name: 'Meat Chic Wors Pap & Gravy', price: 55, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1156', name: 'Meat Wors Pap & Gravy', price: 45, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1108', name: 'Ox Liver 1Kg', price: 55, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1069', name: 'Ox Liver 2.5Kg', price: 100, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1065', name: 'Oxl Liver 500G', price: 27.50, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1163', name: 'Pap And Beef Stew', price: 45, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '80', name: 'Pap And Lamb Stew', price: 35, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '279', name: 'Pap/Beef Stew/Salad', price: 50, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '196', name: 'Pap/Chicken Stew', price: 40, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '324', name: 'Pap/Liver', price: 25, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '31', name: 'Pork  Trotters', price: 40, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '12', name: 'Pork Bones 1Kg', price: 40, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '13', name: 'Pork Bones 2Kg', price: 80, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1042', name: 'Pork Chops 1Kg', price: 70, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '331', name: 'Pork Rashers', price: 55, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '379', name: 'Pork Stew 5Kg', price: 225, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '20', name: 'Pork Trimming', price: 40, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '290', name: 'Pressed Beef Polony', price: 110, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1140', name: 'Prime Rib', price: 89.99, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1048', name: 'Pork Stew 1Kg', price: 50, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '232', name: 'Rice / Beef Stew', price: 45, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '185', name: 'Sirloin Steak', price: 135, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '201', name: 'Spare Rib Wors Pap Gravy', price: 70, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '93', name: 'Steak And Chips', price: 55, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '96', name: 'Steak Fillet', price: 179.99, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '339', name: 'Steak/Chicken/Pap', price: 60, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '172', name: 'Steak/Wors/Chick/Tam/Grav', price: 70, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '170', name: 'Steak/Wors/Tam/Gravy', price: 60, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1142', name: 'T Bone Steak', price: 130, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '211', name: 'T Bone/Wors/ Pap/ Gravy', price: 50, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '94', name: 'Wors And Chips', price: 45, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '244', name: 'Wors Roll', price: 25, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1031', name: 'Wors', price: 36, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '60', name: 'X2 Meat X1 Wors Pap & Gravy R45', price: 55, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '173', name: 'X2Steak/Wors/Tam/Pap', price: 70, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1124', name: '[Halaal] Briscket', price: 130, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1208', name: 'Beef Steak P Kg', price: 130, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1135', name: 'Beef Stirfry', price: 130, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '338', name: 'Chicken Necks And Gizzards', price: 25, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '51', name: 'Extra Meat', price: 30, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '21', name: 'Extra Wors', price: 15, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '291', name: 'Lamb Chops*', price: 140, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1207', name: 'Lamb Leg', price: 179.99, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1151', name: 'Lamb Liver', price: 20, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1181', name: 'Lamb Neck', price: 159.99, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1180', name: 'Lamb Rib', price: 130, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '376', name: 'Lamb Rib', price: 25, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1178', name: 'Lamb Rib Chops', price: 189.99, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '384', name: 'Lamb Rib Wors & Gravy', price: 60, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1182', name: 'Lamb Shanks', price: 180, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1200', name: 'Lamb Stew P Kg', price: 119.99, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '380', name: 'Pork Chops 5Kg', price: 300, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '351', name: 'Rump Steak', price: 135, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '375', name: 'Sparerib & Steak Pap & Gravy', price: 70, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '381', name: 'Steak & Chicken', price: 60, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '385', name: 'Steak / Lamb Rib Pap & Gravy', price: 60, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '395', name: 'Steak Wors Chicken With Rice', price: 75, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '394', name: 'Steak Wors With Rice', price: 65, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '284', name: 'Steak/Wors/Stamp', price: 50, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '1198', name: 'Tenderised Steak', price: 70, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '333', name: 'Wors Rolls', price: 20, unit: 'Each', category: 'Meat & Protein', image: '', emoji: '🥩' },
  { stock_code: '344', name: '1 Tray', price: 65, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '186', name: '1Kg Mala Mugodu', price: 40, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '207', name: '1Kg Makanyanise', price: 32, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '174', name: '20Kg Makanyanise', price: 580, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '156', name: '2Kg Makanyanise', price: 64, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1107', name: '330G Makanyanise', price: 12, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '208', name: '3Kg Makanyanise', price: 96, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '360', name: '500G Gizzards', price: 17.50, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1096', name: '500G Intestine', price: 18, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '155', name: '5Kg Makanyanise', price: 160, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '40', name: 'Artchaar', price: 50, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '151', name: 'Beetroot Salad', price: 5, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '130', name: 'Black Lentils 200G', price: 10, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '313', name: 'Black Pepper', price: 15, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '311', name: 'Bottel Chillies', price: 50, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '164', name: 'Braai Pack', price: 73.28, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '69', name: 'Butcher Polony', price: 100, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '367', name: 'Bokkoors', price: 25, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '137', name: 'Bulk Mince', price: 80, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '152', name: 'Carrot Salad', price: 5, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1112', name: 'Chilli Bites', price: 349.99, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '3', name: 'Chilli Mutton Sausage', price: 96, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1123', name: 'Chuck', price: 130, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '213', name: 'Club Special', price: 140, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1012', name: 'Cow Head', price: 260, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '71', name: 'Disc', price: 560, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1085', name: 'Disc', price: 1.43, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '82', name: 'Disc', price: 5, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '45', name: 'Discontinued', price: 2, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '110', name: 'Dragon', price: 10, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '125', name: 'Durban Masala 100G', price: 25, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '126', name: 'Durban Masala 200G', price: 45, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '56', name: 'Extra Gravy', price: 10, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '387', name: 'Extra Hlogo Gravy', price: 30, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '249', name: 'Fine Jeeroo', price: 28, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '111', name: 'Fire Lighters', price: 35, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '220', name: 'Goolash', price: 130, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '183', name: 'Half Skop Uncooked', price: 60, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '150', name: 'Halfskop', price: 35, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '159', name: 'Hamper 1Kg', price: 710, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '161', name: 'Hamper 2.5Kg', price: 2050, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '160', name: 'Hamper 2Kg', price: 1140, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '158', name: 'Hamper 500G', price: 310, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1169', name: 'I.Q.F Mix Portions 2Kg', price: 95, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '265', name: 'Itsy Bitsy', price: 20, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1191', name: 'Lean Mince Per Kg', price: 110, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '167', name: 'Malamugodu', price: 20, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '329', name: 'Merinated Drumsticks', price: 70, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '330', name: 'Merinated Wings', price: 70, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '287', name: 'Mince', price: 90, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '327', name: 'Mini Chili Wheels', price: 239.99, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '214', name: 'Mini Club Special', price: 70, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '120', name: 'Mix Masala 100G', price: 25, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '119', name: 'Mix Masala 200G', price: 45, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '247', name: 'Mixed Portions Per Kg', price: 2250, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '203', name: 'Mogodu Only', price: 30, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '123', name: 'Mother Inlaw 100G', price: 25, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '122', name: 'Mother Inlaw 200G', price: 40, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '4', name: 'Nuckles 2Kg', price: 100, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1201', name: 'Nuckles 5Kg', price: 175, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '218', name: 'Peanuts', price: 5, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '169', name: 'Pens En Pooitjies', price: 35, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '147', name: 'Pens/Pootjies/Stamp', price: 45, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '124', name: 'Pink Lentils 200G', price: 15, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '140', name: 'Pink Lentils 400G', price: 30, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '235', name: 'Plastic Bag', price: 1, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '104', name: 'Plastic Cup', price: 1, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1056', name: 'Packed Makananjies', price: 620, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '282', name: 'Salamie', price: 85, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '115', name: 'Skaap Pens En Poot', price: 80, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '142', name: 'Skaap Pootjies', price: 50, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '86', name: 'Small Atchar', price: 6, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '241', name: 'Spa Letta', price: 22, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '118', name: 'Special Mix Masala 100G', price: 25, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '168', name: 'Stamp / Stew', price: 45, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '109', name: 'Switch', price: 12, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '347', name: 'Six Gun Grill 200G', price: 25, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '210', name: 'T Bone', price: 30, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1119', name: 'T-Bone Blocks', price: 102.99, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1120', name: 'T-Bone Portions', price: 104.99, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '129', name: 'Tumeric 100G', price: 15, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '231', name: 'Turkey Drums', price: 58, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '127', name: 'White Pepper 100G', price: 20, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '303', name: 'Wood Spoon', price: 15, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '389', name: 'Babalas Mix', price: 320, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '377', name: 'Cow Head', price: 450, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '374', name: 'Cow Heels', price: 40, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '73', name: 'Disc', price: 950, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1055', name: 'Disc', price: 550, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '72', name: 'Disc', price: 270, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1153', name: 'Disc', price: 265, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '337', name: 'Fire Sticks', price: 15, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '336', name: 'Firestarter Kit', price: 50, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '227', name: 'Fomo', price: 3, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '346', name: 'Hout', price: 40, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '352', name: 'Ice Cream Cup', price: 10, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '64', name: 'Mix Mala Mugodu', price: 162.50, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '165', name: 'Ox Tail', price: 100, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '70', name: 'Plastic Bag', price: 1, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '300', name: 'Prawns 2Kg', price: 300, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1141', name: 'Sliced Billtong', price: 299, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '157', name: 'Stamp', price: 15, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '1077', name: 'Voortrekker', price: 40.25, unit: 'Each', category: 'Other', image: '', emoji: '📦' },
  { stock_code: '153', name: 'Grapes', price: 25, unit: 'Each', category: 'Produce', image: '', emoji: '🥦' },
  { stock_code: '294', name: 'Pumkin', price: 5, unit: 'Each', category: 'Produce', image: '', emoji: '🥦' },
  { stock_code: '280', name: '48 X Toilet Paper', price: 170, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '132', name: '6 X Toilet Paper', price: 25, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '304', name: 'Braai Pak', price: 35, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '234', name: 'Briyani', price: 50, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '309', name: 'Curry Chillies', price: 100, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '85', name: 'Curry Chillies Small', price: 10, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '1173', name: 'Extra Pap', price: 10, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '242', name: 'Extra Rice', price: 15, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '386', name: 'Hlogo And Pap', price: 45, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '388', name: 'Hardbody & Pap', price: 45, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '90', name: 'Meduim Chips', price: 42, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '1087', name: 'Mini Chips', price: 15, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '88', name: 'Mini Chips', price: 15, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '149', name: 'Pap/Halfskop', price: 40, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '10', name: 'Pap/Malamugodu', price: 45, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '274', name: 'Pens/Pooitjies/Rice', price: 45, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '146', name: 'Pens/Pootjies/Pap', price: 45, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '262', name: 'Pie And Salad Combo', price: 45, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '133', name: 'Pro Soft Toilet Paper', price: 170, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '285', name: 'Prosoft Toilet Paper X6', price: 30, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '189', name: 'Simba Chips', price: 7, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '1196', name: 'Toilet Paper X48', price: 215, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '317', name: 'X12 Toilet Paper', price: 60, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '391', name: 'Mutton Curry', price: 35, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '393', name: 'Mutton Curry & Pap', price: 60, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '301', name: 'Mutton Curry / Rice', price: 60, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '288', name: 'Pap/Gravy', price: 20, unit: 'Each', category: 'Ready-to-Eat', image: '', emoji: '🍛' },
  { stock_code: '222', name: 'Coconut Biscuits', price: 10, unit: 'Each', category: 'Snacks', image: '', emoji: '🍪' },
  { stock_code: '216', name: 'Shortbread Biscuits', price: 10, unit: 'Each', category: 'Snacks', image: '', emoji: '🍪' }
];

export function mapToProduct(p) {
  return {
    id: p.stock_code || String(p.name).toLowerCase().replace(/\s+/g, '-'),
    name: p.name,
    category: ['Meat & Protein','Eggs & Dairy','Groceries','Produce','Sausages'].includes(p.category) ? 'raw' : 'cooked',
    categoryLabel: p.category,
    description: '',
    price: parseFloat(p.price) || 0,
    unit: p.unit || 'each',
    image: p.image || (p.emoji || ''),
    emoji: p.emoji || '',
    image_url: p.image || (p.emoji || ''),
    is_active: true,
    available: true,
    stockQty: 100,
    isSpecial: false,
    discount_price: null,
    createdAt: new Date().toISOString()
  };
}

export function getCategoryEmoji(category) {
  const map = {"Beverages": "\ud83e\udd64", "Eggs & Dairy": "\ud83e\udd5a", "Groceries": "\ud83d\uded2", "Meat & Protein": "\ud83e\udd69", "Other": "\ud83d\udce6", "Produce": "\ud83e\udd66", "Ready-to-Eat": "\ud83c\udf5b", "Snacks": "\ud83c\udf6a", "Sausages": "\ud83c\udf2d"};
  return map[category] || '📦';
}